apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: {{ TENANT_NS }}
spec:
  hard:
    requests.cpu: "8"
    requests.memory: "16Gi"
    limits.cpu: "16"
    limits.memory: "32Gi"
    pods: "20"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
# Default resource limits — safety net for any container that doesn't set
# explicit limits, ensuring it can be admitted under the ResourceQuota above.
# Note: kmcp ≥ 0.2.3 supports setting resources directly on MCPServer CRs
# via spec.deployment.resources (see sample-mcpserver.yaml).
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: {{ TENANT_NS }}
spec:
  limits:
    - type: Container
      default:
        cpu: 200m
        memory: 256Mi
      defaultRequest:
        cpu: 50m
        memory: 64Mi
