// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: init.proto

package initpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InitRequest is empty; the guest needs no parameters.
type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_init_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_init_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_init_proto_rawDescGZIP(), []int{0}
}

// InitResponse carries everything the guest needs to boot,
// configure, and handle the client request.
type InitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Network configuration for the guest's eth0 interface.
	Network *NetworkConfig `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	// Files to inject into the guest filesystem.
	Files []*FileConfig `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	// Payload is the client's request body, forwarded from
	// the waypoint's POST /run request.
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Payload headers from the client request that should
	// be forwarded to the agent (e.g., Content-Type).
	PayloadHeaders map[string]string `protobuf:"bytes,4,rep,name=payload_headers,json=payloadHeaders,proto3" json:"payload_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Agent port — the port the agent listens on inside
	// the VM (e.g., 8080).
	AgentPort     int32 `protobuf:"varint,5,opt,name=agent_port,json=agentPort,proto3" json:"agent_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_init_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_init_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_init_proto_rawDescGZIP(), []int{1}
}

func (x *InitResponse) GetNetwork() *NetworkConfig {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *InitResponse) GetFiles() []*FileConfig {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *InitResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InitResponse) GetPayloadHeaders() map[string]string {
	if x != nil {
		return x.PayloadHeaders
	}
	return nil
}

func (x *InitResponse) GetAgentPort() int32 {
	if x != nil {
		return x.AgentPort
	}
	return 0
}

// NetworkConfig for the guest's eth0 interface.
type NetworkConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IP address (e.g., "169.254.1.2").
	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	// Default gateway (e.g., "169.254.1.1").
	Gateway string `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	// Prefix length (e.g., 32).
	PrefixLen int32 `protobuf:"varint,3,opt,name=prefix_len,json=prefixLen,proto3" json:"prefix_len,omitempty"`
	// MTU matching the host TAP device.
	Mtu           int32 `protobuf:"varint,4,opt,name=mtu,proto3" json:"mtu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConfig) Reset() {
	*x = NetworkConfig{}
	mi := &file_init_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfig) ProtoMessage() {}

func (x *NetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_init_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfig.ProtoReflect.Descriptor instead.
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return file_init_proto_rawDescGZIP(), []int{2}
}

func (x *NetworkConfig) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NetworkConfig) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *NetworkConfig) GetPrefixLen() int32 {
	if x != nil {
		return x.PrefixLen
	}
	return 0
}

func (x *NetworkConfig) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

// FileConfig defines a file to inject into the guest.
type FileConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute path in the guest filesystem.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Raw file content.
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Unix permission bits (e.g., 0644).
	Mode          uint32 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileConfig) Reset() {
	*x = FileConfig{}
	mi := &file_init_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileConfig) ProtoMessage() {}

func (x *FileConfig) ProtoReflect() protoreflect.Message {
	mi := &file_init_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileConfig.ProtoReflect.Descriptor instead.
func (*FileConfig) Descriptor() ([]byte, []int) {
	return file_init_proto_rawDescGZIP(), []int{3}
}

func (x *FileConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileConfig) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileConfig) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

// StreamRequest carries one chunk of SSE data from the
// agent's response, or signals completion.
type StreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SSE data chunk. Empty when done=true.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// True when the agent's response is complete.
	Done bool `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	// Error message if the agent request failed.
	// Non-empty only when done=true and the request errored.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_init_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_init_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_init_proto_rawDescGZIP(), []int{4}
}

func (x *StreamRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StreamRequest) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *StreamRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// StreamResponse is an acknowledgment.
type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_init_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_init_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_init_proto_rawDescGZIP(), []int{5}
}

var File_init_proto protoreflect.FileDescriptor

const file_init_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"init.proto\x12\x10executor.init.v1\"\r\n" +
	"\vInitRequest\"\xd6\x02\n" +
	"\fInitResponse\x129\n" +
	"\anetwork\x18\x01 \x01(\v2\x1f.executor.init.v1.NetworkConfigR\anetwork\x122\n" +
	"\x05files\x18\x02 \x03(\v2\x1c.executor.init.v1.FileConfigR\x05files\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12[\n" +
	"\x0fpayload_headers\x18\x04 \x03(\v22.executor.init.v1.InitResponse.PayloadHeadersEntryR\x0epayloadHeaders\x12\x1d\n" +
	"\n" +
	"agent_port\x18\x05 \x01(\x05R\tagentPort\x1aA\n" +
	"\x13PayloadHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\rNetworkConfig\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x18\n" +
	"\agateway\x18\x02 \x01(\tR\agateway\x12\x1d\n" +
	"\n" +
	"prefix_len\x18\x03 \x01(\x05R\tprefixLen\x12\x10\n" +
	"\x03mtu\x18\x04 \x01(\x05R\x03mtu\"N\n" +
	"\n" +
	"FileConfig\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\"M\n" +
	"\rStreamRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x10\n" +
	"\x0eStreamResponse2\xa1\x01\n" +
	"\vInitControl\x12E\n" +
	"\x04Init\x12\x1d.executor.init.v1.InitRequest\x1a\x1e.executor.init.v1.InitResponse\x12K\n" +
	"\x06Stream\x12\x1f.executor.init.v1.StreamRequest\x1a .executor.init.v1.StreamResponseBEZCgithub.com/siyanzhu/agentic-platform/executor/internal/vsock/initpbb\x06proto3"

var (
	file_init_proto_rawDescOnce sync.Once
	file_init_proto_rawDescData []byte
)

func file_init_proto_rawDescGZIP() []byte {
	file_init_proto_rawDescOnce.Do(func() {
		file_init_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_init_proto_rawDesc), len(file_init_proto_rawDesc)))
	})
	return file_init_proto_rawDescData
}

var file_init_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_init_proto_goTypes = []any{
	(*InitRequest)(nil),    // 0: executor.init.v1.InitRequest
	(*InitResponse)(nil),   // 1: executor.init.v1.InitResponse
	(*NetworkConfig)(nil),  // 2: executor.init.v1.NetworkConfig
	(*FileConfig)(nil),     // 3: executor.init.v1.FileConfig
	(*StreamRequest)(nil),  // 4: executor.init.v1.StreamRequest
	(*StreamResponse)(nil), // 5: executor.init.v1.StreamResponse
	nil,                    // 6: executor.init.v1.InitResponse.PayloadHeadersEntry
}
var file_init_proto_depIdxs = []int32{
	2, // 0: executor.init.v1.InitResponse.network:type_name -> executor.init.v1.NetworkConfig
	3, // 1: executor.init.v1.InitResponse.files:type_name -> executor.init.v1.FileConfig
	6, // 2: executor.init.v1.InitResponse.payload_headers:type_name -> executor.init.v1.InitResponse.PayloadHeadersEntry
	0, // 3: executor.init.v1.InitControl.Init:input_type -> executor.init.v1.InitRequest
	4, // 4: executor.init.v1.InitControl.Stream:input_type -> executor.init.v1.StreamRequest
	1, // 5: executor.init.v1.InitControl.Init:output_type -> executor.init.v1.InitResponse
	5, // 6: executor.init.v1.InitControl.Stream:output_type -> executor.init.v1.StreamResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_init_proto_init() }
func file_init_proto_init() {
	if File_init_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_init_proto_rawDesc), len(file_init_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_init_proto_goTypes,
		DependencyIndexes: file_init_proto_depIdxs,
		MessageInfos:      file_init_proto_msgTypes,
	}.Build()
	File_init_proto = out.File
	file_init_proto_goTypes = nil
	file_init_proto_depIdxs = nil
}
