// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: init.proto

package initpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InitRequest is empty; the guest needs no parameters.
type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_init_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_init_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_init_proto_rawDescGZIP(), []int{0}
}

// InitResponse carries everything the guest needs to configure
// itself before starting the agent.
type InitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Network configuration for the guest's eth0 interface.
	Network *NetworkConfig `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	// Files to inject into the guest filesystem.
	Files         []*FileConfig `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_init_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_init_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_init_proto_rawDescGZIP(), []int{1}
}

func (x *InitResponse) GetNetwork() *NetworkConfig {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *InitResponse) GetFiles() []*FileConfig {
	if x != nil {
		return x.Files
	}
	return nil
}

// NetworkConfig for the guest's eth0 interface.
type NetworkConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IP address (e.g., "192.168.1.5").
	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	// Default gateway (e.g., "192.168.1.1").
	Gateway string `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	// Prefix length (e.g., 24).
	PrefixLen int32 `protobuf:"varint,3,opt,name=prefix_len,json=prefixLen,proto3" json:"prefix_len,omitempty"`
	// MTU matching the host interface.
	Mtu           int32 `protobuf:"varint,4,opt,name=mtu,proto3" json:"mtu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConfig) Reset() {
	*x = NetworkConfig{}
	mi := &file_init_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfig) ProtoMessage() {}

func (x *NetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_init_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfig.ProtoReflect.Descriptor instead.
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return file_init_proto_rawDescGZIP(), []int{2}
}

func (x *NetworkConfig) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NetworkConfig) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *NetworkConfig) GetPrefixLen() int32 {
	if x != nil {
		return x.PrefixLen
	}
	return 0
}

func (x *NetworkConfig) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

// FileConfig defines a file to inject into the guest.
type FileConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute path in the guest filesystem.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Raw file content.
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Unix permission bits (e.g., 0644).
	Mode          uint32 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileConfig) Reset() {
	*x = FileConfig{}
	mi := &file_init_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileConfig) ProtoMessage() {}

func (x *FileConfig) ProtoReflect() protoreflect.Message {
	mi := &file_init_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileConfig.ProtoReflect.Descriptor instead.
func (*FileConfig) Descriptor() ([]byte, []int) {
	return file_init_proto_rawDescGZIP(), []int{3}
}

func (x *FileConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileConfig) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileConfig) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

var File_init_proto protoreflect.FileDescriptor

const file_init_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"init.proto\x12\x10executor.init.v1\"\r\n" +
	"\vInitRequest\"}\n" +
	"\fInitResponse\x129\n" +
	"\anetwork\x18\x01 \x01(\v2\x1f.executor.init.v1.NetworkConfigR\anetwork\x122\n" +
	"\x05files\x18\x02 \x03(\v2\x1c.executor.init.v1.FileConfigR\x05files\"j\n" +
	"\rNetworkConfig\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x18\n" +
	"\agateway\x18\x02 \x01(\tR\agateway\x12\x1d\n" +
	"\n" +
	"prefix_len\x18\x03 \x01(\x05R\tprefixLen\x12\x10\n" +
	"\x03mtu\x18\x04 \x01(\x05R\x03mtu\"N\n" +
	"\n" +
	"FileConfig\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode2T\n" +
	"\vInitControl\x12E\n" +
	"\x04Init\x12\x1d.executor.init.v1.InitRequest\x1a\x1e.executor.init.v1.InitResponseBEZCgithub.com/siyanzhu/agentic-platform/executor/internal/vsock/initpbb\x06proto3"

var (
	file_init_proto_rawDescOnce sync.Once
	file_init_proto_rawDescData []byte
)

func file_init_proto_rawDescGZIP() []byte {
	file_init_proto_rawDescOnce.Do(func() {
		file_init_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_init_proto_rawDesc), len(file_init_proto_rawDesc)))
	})
	return file_init_proto_rawDescData
}

var file_init_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_init_proto_goTypes = []any{
	(*InitRequest)(nil),   // 0: executor.init.v1.InitRequest
	(*InitResponse)(nil),  // 1: executor.init.v1.InitResponse
	(*NetworkConfig)(nil), // 2: executor.init.v1.NetworkConfig
	(*FileConfig)(nil),    // 3: executor.init.v1.FileConfig
}
var file_init_proto_depIdxs = []int32{
	2, // 0: executor.init.v1.InitResponse.network:type_name -> executor.init.v1.NetworkConfig
	3, // 1: executor.init.v1.InitResponse.files:type_name -> executor.init.v1.FileConfig
	0, // 2: executor.init.v1.InitControl.Init:input_type -> executor.init.v1.InitRequest
	1, // 3: executor.init.v1.InitControl.Init:output_type -> executor.init.v1.InitResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_init_proto_init() }
func file_init_proto_init() {
	if File_init_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_init_proto_rawDesc), len(file_init_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_init_proto_goTypes,
		DependencyIndexes: file_init_proto_depIdxs,
		MessageInfos:      file_init_proto_msgTypes,
	}.Build()
	File_init_proto = out.File
	file_init_proto_goTypes = nil
	file_init_proto_depIdxs = nil
}
