// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: init.proto
package initpb

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
)

type InitControlService interface {
	Init(context.Context, *InitRequest) (*InitResponse, error)
	EmitEvent(context.Context, *EmitEventRequest) (*EmitEventResponse, error)
}

func RegisterInitControlService(srv *ttrpc.Server, svc InitControlService) {
	srv.RegisterService("executor.init.v1.InitControl", &ttrpc.ServiceDesc{
		Methods: map[string]ttrpc.Method{
			"Init": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req InitRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.Init(ctx, &req)
			},
			"EmitEvent": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req EmitEventRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.EmitEvent(ctx, &req)
			},
		},
	})
}

type initcontrolClient struct {
	client *ttrpc.Client
}

func NewInitControlClient(client *ttrpc.Client) InitControlService {
	return &initcontrolClient{
		client: client,
	}
}

func (c *initcontrolClient) Init(ctx context.Context, req *InitRequest) (*InitResponse, error) {
	var resp InitResponse
	if err := c.client.Call(ctx, "executor.init.v1.InitControl", "Init", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *initcontrolClient) EmitEvent(ctx context.Context, req *EmitEventRequest) (*EmitEventResponse, error) {
	var resp EmitEventResponse
	if err := c.client.Call(ctx, "executor.init.v1.InitControl", "EmitEvent", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
