# Control-plane AWS resource outputs
# Generated by scripts/phase3a/00-create-aws-resources.sh
# 2026-03-29T13:57:08Z

# ── RDS ──
RDS_ENDPOINT=agentic-cp-postgres.c8wxny7wgs2y.us-east-1.rds.amazonaws.com
DB_PASSWORD=jVr5iWOKRaO3JIXJT8bGo6OnrOZH4hlx
RDS_DATABASE_URL=postgresql://postgres:jVr5iWOKRaO3JIXJT8bGo6OnrOZH4hlx@agentic-cp-postgres.c8wxny7wgs2y.us-east-1.rds.amazonaws.com:5432/langfuse
KEYCLOAK_DB_PASSWORD=8F08SybiSqTvDmNxBUnKW6cmYoAsaz
KEYCLOAK_DATABASE_URL=postgresql://keycloak:8F08SybiSqTvDmNxBUnKW6cmYoAsaz@agentic-cp-postgres.c8wxny7wgs2y.us-east-1.rds.amazonaws.com:5432/keycloak
OPENFGA_DB_PASSWORD=FBjdZ64wxiU72jv5GUxVW3CewbKgLGmG
OPENFGA_DATABASE_URL=postgresql://openfga:FBjdZ64wxiU72jv5GUxVW3CewbKgLGmG@agentic-cp-postgres.c8wxny7wgs2y.us-east-1.rds.amazonaws.com:5432/openfga
AGENTREGISTRY_DB_PASSWORD=mI2fxC8Oipc8szgI3LvDmN1b2L33NvN
AGENTREGISTRY_DATABASE_URL=postgresql://agentregistry:mI2fxC8Oipc8szgI3LvDmN1b2L33NvN@agentic-cp-postgres.c8wxny7wgs2y.us-east-1.rds.amazonaws.com:5432/agentregistry

# ── ElastiCache ──
REDIS_ENDPOINT=master.agentic-cp-redis.oay4mu.use1.cache.amazonaws.com
REDIS_PASSWORD=ylne52AHVP89m9HwXQHLxDjRZU44C2I
REDIS_URL=rediss://:ylne52AHVP89m9HwXQHLxDjRZU44C2I@master.agentic-cp-redis.oay4mu.use1.cache.amazonaws.com:6379

# ── S3 ──
S3_BUCKET=agentic-platform-langfuse-cp
S3_REGION=us-east-1
NEXTAUTH_SECRET=rO/K46hnUDJq74ofqYUiSr9LyJdRombgh4VJaz+NAFE=
ENCRYPTION_KEY=1c1c76c0b1dfa9c813afb2047f5152f21fa36c1811239ebbd522e1017fd734db
SALT=kb3wmvEWxs22NZy5yt1uqhc+NPQFJZNl3qkBpiPanzU=
KEYCLOAK_ADMIN_PASSWORD=FxfXLLsfpJKV2goGqWnwSenCJn9lAdAj
LANGFUSE_PUBLIC_KEY=pk-lf-f317142bf8130aef7fbe896ae8f210c0
LANGFUSE_SECRET_KEY=sk-lf-90b524388728bc243c145897dd26ebffc4cc6644dc348ea0f0188a8c773d63a0
LB_CONTROLLER_ROLE_ARN=arn:aws:iam::268558157000:role/agentic-cp-aws-lb-controller
VPC_ID=vpc-0633964670a3bb7ff
