//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIKeyCredentialRef) DeepCopyInto(out *APIKeyCredentialRef) {
	*out = *in
	out.ProviderRef = in.ProviderRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIKeyCredentialRef.
func (in *APIKeyCredentialRef) DeepCopy() *APIKeyCredentialRef {
	if in == nil {
		return nil
	}
	out := new(APIKeyCredentialRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIKeyProviderSpec) DeepCopyInto(out *APIKeyProviderSpec) {
	*out = *in
	in.APIKeySecretRef.DeepCopyInto(&out.APIKeySecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIKeyProviderSpec.
func (in *APIKeyProviderSpec) DeepCopy() *APIKeyProviderSpec {
	if in == nil {
		return nil
	}
	out := new(APIKeyProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialProvider) DeepCopyInto(out *CredentialProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialProvider.
func (in *CredentialProvider) DeepCopy() *CredentialProvider {
	if in == nil {
		return nil
	}
	out := new(CredentialProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CredentialProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialProviderList) DeepCopyInto(out *CredentialProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CredentialProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialProviderList.
func (in *CredentialProviderList) DeepCopy() *CredentialProviderList {
	if in == nil {
		return nil
	}
	out := new(CredentialProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CredentialProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialProviderSpec) DeepCopyInto(out *CredentialProviderSpec) {
	*out = *in
	if in.OAuth != nil {
		in, out := &in.OAuth, &out.OAuth
		*out = new(OAuthProviderSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.APIKey != nil {
		in, out := &in.APIKey, &out.APIKey
		*out = new(APIKeyProviderSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialProviderSpec.
func (in *CredentialProviderSpec) DeepCopy() *CredentialProviderSpec {
	if in == nil {
		return nil
	}
	out := new(CredentialProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialProviderStatus) DeepCopyInto(out *CredentialProviderStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialProviderStatus.
func (in *CredentialProviderStatus) DeepCopy() *CredentialProviderStatus {
	if in == nil {
		return nil
	}
	out := new(CredentialProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityProviderConfig) DeepCopyInto(out *IdentityProviderConfig) {
	*out = *in
	if in.Audiences != nil {
		in, out := &in.Audiences, &out.Audiences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedClients != nil {
		in, out := &in.AllowedClients, &out.AllowedClients
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedScopes != nil {
		in, out := &in.AllowedScopes, &out.AllowedScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityProviderConfig.
func (in *IdentityProviderConfig) DeepCopy() *IdentityProviderConfig {
	if in == nil {
		return nil
	}
	out := new(IdentityProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuthAuthorizationServerMetadata) DeepCopyInto(out *OAuthAuthorizationServerMetadata) {
	*out = *in
	if in.ResponseTypes != nil {
		in, out := &in.ResponseTypes, &out.ResponseTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TokenEndpointAuthMethods != nil {
		in, out := &in.TokenEndpointAuthMethods, &out.TokenEndpointAuthMethods
		*out = make([]TokenEndpointAuthMethod, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuthAuthorizationServerMetadata.
func (in *OAuthAuthorizationServerMetadata) DeepCopy() *OAuthAuthorizationServerMetadata {
	if in == nil {
		return nil
	}
	out := new(OAuthAuthorizationServerMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuthCredentialRef) DeepCopyInto(out *OAuthCredentialRef) {
	*out = *in
	out.ProviderRef = in.ProviderRef
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuthCredentialRef.
func (in *OAuthCredentialRef) DeepCopy() *OAuthCredentialRef {
	if in == nil {
		return nil
	}
	out := new(OAuthCredentialRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuthDiscovery) DeepCopyInto(out *OAuthDiscovery) {
	*out = *in
	if in.AuthorizationServerMetadata != nil {
		in, out := &in.AuthorizationServerMetadata, &out.AuthorizationServerMetadata
		*out = new(OAuthAuthorizationServerMetadata)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuthDiscovery.
func (in *OAuthDiscovery) DeepCopy() *OAuthDiscovery {
	if in == nil {
		return nil
	}
	out := new(OAuthDiscovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuthProviderSpec) DeepCopyInto(out *OAuthProviderSpec) {
	*out = *in
	in.ClientSecretRef.DeepCopyInto(&out.ClientSecretRef)
	in.Discovery.DeepCopyInto(&out.Discovery)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuthProviderSpec.
func (in *OAuthProviderSpec) DeepCopy() *OAuthProviderSpec {
	if in == nil {
		return nil
	}
	out := new(OAuthProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantConfig) DeepCopyInto(out *TenantConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantConfig.
func (in *TenantConfig) DeepCopy() *TenantConfig {
	if in == nil {
		return nil
	}
	out := new(TenantConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantConfigList) DeepCopyInto(out *TenantConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TenantConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantConfigList.
func (in *TenantConfigList) DeepCopy() *TenantConfigList {
	if in == nil {
		return nil
	}
	out := new(TenantConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantConfigSpec) DeepCopyInto(out *TenantConfigSpec) {
	*out = *in
	in.IdentityProvider.DeepCopyInto(&out.IdentityProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantConfigSpec.
func (in *TenantConfigSpec) DeepCopy() *TenantConfigSpec {
	if in == nil {
		return nil
	}
	out := new(TenantConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantConfigStatus) DeepCopyInto(out *TenantConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantConfigStatus.
func (in *TenantConfigStatus) DeepCopy() *TenantConfigStatus {
	if in == nil {
		return nil
	}
	out := new(TenantConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tool) DeepCopyInto(out *Tool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tool.
func (in *Tool) DeepCopy() *Tool {
	if in == nil {
		return nil
	}
	out := new(Tool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Tool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolContainer) DeepCopyInto(out *ToolContainer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolContainer.
func (in *ToolContainer) DeepCopy() *ToolContainer {
	if in == nil {
		return nil
	}
	out := new(ToolContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolCredentials) DeepCopyInto(out *ToolCredentials) {
	*out = *in
	if in.OAuth != nil {
		in, out := &in.OAuth, &out.OAuth
		*out = new(OAuthCredentialRef)
		(*in).DeepCopyInto(*out)
	}
	if in.APIKeys != nil {
		in, out := &in.APIKeys, &out.APIKeys
		*out = make([]APIKeyCredentialRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolCredentials.
func (in *ToolCredentials) DeepCopy() *ToolCredentials {
	if in == nil {
		return nil
	}
	out := new(ToolCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolList) DeepCopyInto(out *ToolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Tool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolList.
func (in *ToolList) DeepCopy() *ToolList {
	if in == nil {
		return nil
	}
	out := new(ToolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ToolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolScaling) DeepCopyInto(out *ToolScaling) {
	*out = *in
	if in.MinScale != nil {
		in, out := &in.MinScale, &out.MinScale
		*out = new(int32)
		**out = **in
	}
	if in.MaxScale != nil {
		in, out := &in.MaxScale, &out.MaxScale
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolScaling.
func (in *ToolScaling) DeepCopy() *ToolScaling {
	if in == nil {
		return nil
	}
	out := new(ToolScaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolSpec) DeepCopyInto(out *ToolSpec) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(ToolCredentials)
		(*in).DeepCopyInto(*out)
	}
	if in.InputSchema != nil {
		in, out := &in.InputSchema, &out.InputSchema
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	out.Container = in.Container
	if in.Scaling != nil {
		in, out := &in.Scaling, &out.Scaling
		*out = new(ToolScaling)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolSpec.
func (in *ToolSpec) DeepCopy() *ToolSpec {
	if in == nil {
		return nil
	}
	out := new(ToolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolStatus) DeepCopyInto(out *ToolStatus) {
	*out = *in
	if in.KnativeServiceRef != nil {
		in, out := &in.KnativeServiceRef, &out.KnativeServiceRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolStatus.
func (in *ToolStatus) DeepCopy() *ToolStatus {
	if in == nil {
		return nil
	}
	out := new(ToolStatus)
	in.DeepCopyInto(out)
	return out
}
