# Example 03: Governed AI Egress
#
# Demonstrates per-tenant egress governance via the AgentGateway waypoint:
#   - Transparent mesh interception (agent thinks it talks to api.anthropic.com)
#   - Prompt guards (regex-based PII filtering: SSN, credit card)
#   - Credential injection (real API key injected by waypoint)
#   - TLS origination (HTTP inside mesh → HTTPS to external API)
#
# Prerequisites:
#   1. Platform deployed (platform/manifests/)
#   2. Real API key secret created:
#        kubectl create secret generic anthropic-api-secret \
#          -n example-egress \
#          --from-literal=Authorization="$ANTHROPIC_API_KEY"
#
# Deploy:  kubectl apply -f manifests.yaml
# Cleanup: kubectl delete -f manifests.yaml

# ── Namespace ──────────────────────────────────────────────────────────────────
apiVersion: v1
kind: Namespace
metadata:
  name: example-egress
  labels:
    platform.agentic.io/gateway-discovery: "true"
    platform.agentic.io/tenant: "true"
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: agentgateway-waypoint
    istio.io/ingress-use-waypoint: "true"
---
# ── RBAC ───────────────────────────────────────────────────────────────────────
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-agent-developer-binding
  namespace: example-egress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tenant-agent-developer
subjects:
  - kind: Group
    name: "tenant-egress-developers"
    apiGroup: rbac.authorization.k8s.io
---
# ── Network Policy ─────────────────────────────────────────────────────────────
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tenant-isolation
  namespace: example-egress
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: example-egress
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kagent-system
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: agentgateway-system
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
    - from:
        - ipBlock:
            cidr: 169.254.7.127/32
  egress:
    # Same namespace (includes waypoint pod)
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: example-egress
    # DNS
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Langfuse (tracing)
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: langfuse
    # kagent controller
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kagent-system
    # AgentGateway system (for ingress proxy fallback)
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: agentgateway-system
    # Istio control plane
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
    # External traffic — HTTP (mesh-intercepted egress) and HTTPS (direct)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
---
# ── Istio Authorization Policy ─────────────────────────────────────────────────
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: tenant-isolation
  namespace: example-egress
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces:
              - example-egress
    - from:
        - source:
            namespaces:
              - agentgateway-system
    - from:
        - source:
            namespaces:
              - kagent-system
    - from:
        - source:
            namespaces:
              - istio-system
    - from:
        - source:
            namespaces:
              - monitoring
---
# ── Per-Tenant Waypoint ────────────────────────────────────────────────────────
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: agentgateway-waypoint
  namespace: example-egress
  labels:
    platform.agentic.io/component: agentgateway
    istio.io/waypoint-for: service
spec:
  gatewayClassName: agentgateway-waypoint
  listeners:
    - name: mesh
      port: 15008
      protocol: HBONE
      allowedRoutes:
        namespaces:
          from: Same
---
# ── Egress: ServiceEntry ──────────────────────────────────────────────────────
# Makes api.anthropic.com a mesh-external service routed through the waypoint.
# Traffic from agent pods on HTTP:80 is intercepted by ztunnel and forwarded
# to the waypoint, which originates TLS to the real HTTPS:443 endpoint.
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: anthropic-api
  namespace: example-egress
  labels:
    istio.io/use-waypoint: agentgateway-waypoint
spec:
  exportTo:
    - "."
  hosts:
    - api.anthropic.com
  ports:
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  location: MESH_EXTERNAL
  resolution: DNS
---
# ── Egress: AgentgatewayBackend ───────────────────────────────────────────────
# The core of this example: credential injection + prompt guard (PII filtering).
#
# The waypoint reads the real API key from anthropic-api-secret and injects it
# into outbound requests. The prompt guard blocks requests containing SSN or
# credit card patterns before they reach the LLM.
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: anthropic-egress
  namespace: example-egress
spec:
  ai:
    provider:
      anthropic:
        model: claude-sonnet-4-20250514
  policies:
    ai:
      promptGuard:
        request:
          - regex:
              builtins:
                - Ssn
                - CreditCard
              action: Reject
            response:
              message: "Request blocked by tenant policy: PII detected in prompt"
              statusCode: 403
      routes:
        /v1/messages: Messages
        /v1/chat/completions: Completions
        "*": Passthrough
    auth:
      secretRef:
        name: anthropic-api-secret
---
# ── Egress: HTTPRoute ─────────────────────────────────────────────────────────
# Routes api.anthropic.com traffic through the waypoint to the backend above.
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: anthropic-egress
  namespace: example-egress
spec:
  hostnames:
    - api.anthropic.com
  parentRefs:
    - name: agentgateway-waypoint
  rules:
    - backendRefs:
        - group: agentgateway.dev
          kind: AgentgatewayBackend
          name: anthropic-egress
---
# ── LLM Configuration ─────────────────────────────────────────────────────────
# Dummy secret — LiteLLM requires a non-empty API key for validation.
# The real key is injected by the waypoint (via AgentgatewayBackend secretRef).
apiVersion: v1
kind: Secret
metadata:
  name: anthropic-dummy
  namespace: example-egress
type: Opaque
stringData:
  api-key: "not-a-real-key"
---
# ModelConfig points to http://api.anthropic.com (NOT the ingress proxy).
# The mesh transparently intercepts this traffic and routes it through the
# per-tenant waypoint, which applies prompt guards and injects credentials.
apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: default-model-config
  namespace: example-egress
spec:
  provider: Anthropic
  model: claude-sonnet-4-20250514
  apiKeySecret: anthropic-dummy
  apiKeySecretKey: api-key
  anthropic:
    baseUrl: http://api.anthropic.com
---
# ── Agent ──────────────────────────────────────────────────────────────────────
# Simple Declarative chat agent — no custom tools. The governance story is
# entirely at the infrastructure layer (waypoint + prompt guards).
apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: governed-assistant
  namespace: example-egress
  annotations:
    platform.agentic.io/expose: "true"
spec:
  description: "A helpful assistant with per-tenant egress governance (PII filtering, credential injection)"
  type: Declarative
  declarative:
    modelConfig: default-model-config
    systemMessage: |
      You are a helpful assistant. Answer the user's questions clearly and concisely.
    a2aConfig:
      skills:
        - id: general-assistant
          name: General Assistant
          description: "Answer questions and help with tasks"
          tags:
            - chat
            - general
