// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: pool.proto

package poolpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClaimRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pool name (e.g., "poc-agent").
	Pool          string `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimRequest) Reset() {
	*x = ClaimRequest{}
	mi := &file_pool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRequest) ProtoMessage() {}

func (x *ClaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRequest.ProtoReflect.Descriptor instead.
func (*ClaimRequest) Descriptor() ([]byte, []int) {
	return file_pool_proto_rawDescGZIP(), []int{0}
}

func (x *ClaimRequest) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

type ClaimResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the claimed pod.
	PodName string `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	// Pod IP address.
	PodIp string `protobuf:"bytes,2,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	// Port the executor listens on.
	PodPort int32 `protobuf:"varint,3,opt,name=pod_port,json=podPort,proto3" json:"pod_port,omitempty"`
	// Claim ID — passed to the executor via X-Claim-Id header,
	// used by the executor for Renew and Release.
	ClaimId       string `protobuf:"bytes,4,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimResponse) Reset() {
	*x = ClaimResponse{}
	mi := &file_pool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimResponse) ProtoMessage() {}

func (x *ClaimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimResponse.ProtoReflect.Descriptor instead.
func (*ClaimResponse) Descriptor() ([]byte, []int) {
	return file_pool_proto_rawDescGZIP(), []int{1}
}

func (x *ClaimResponse) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *ClaimResponse) GetPodIp() string {
	if x != nil {
		return x.PodIp
	}
	return ""
}

func (x *ClaimResponse) GetPodPort() int32 {
	if x != nil {
		return x.PodPort
	}
	return 0
}

func (x *ClaimResponse) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

type RenewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClaimId       string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewRequest) Reset() {
	*x = RenewRequest{}
	mi := &file_pool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewRequest) ProtoMessage() {}

func (x *RenewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewRequest.ProtoReflect.Descriptor instead.
func (*RenewRequest) Descriptor() ([]byte, []int) {
	return file_pool_proto_rawDescGZIP(), []int{2}
}

func (x *RenewRequest) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

type RenewResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When the lease expires if not renewed again.
	ExpiresAt     string `protobuf:"bytes,1,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewResponse) Reset() {
	*x = RenewResponse{}
	mi := &file_pool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewResponse) ProtoMessage() {}

func (x *RenewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewResponse.ProtoReflect.Descriptor instead.
func (*RenewResponse) Descriptor() ([]byte, []int) {
	return file_pool_proto_rawDescGZIP(), []int{3}
}

func (x *RenewResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClaimId       string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_pool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_pool_proto_rawDescGZIP(), []int{4}
}

func (x *ReleaseRequest) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

type ReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseResponse) Reset() {
	*x = ReleaseResponse{}
	mi := &file_pool_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseResponse) ProtoMessage() {}

func (x *ReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pool_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseResponse) Descriptor() ([]byte, []int) {
	return file_pool_proto_rawDescGZIP(), []int{5}
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_pool_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pool_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_pool_proto_rawDescGZIP(), []int{6}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pools         map[string]*PoolStatus `protobuf:"bytes,1,rep,name=pools,proto3" json:"pools,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_pool_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pool_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_pool_proto_rawDescGZIP(), []int{7}
}

func (x *StatusResponse) GetPools() map[string]*PoolStatus {
	if x != nil {
		return x.Pools
	}
	return nil
}

type PoolStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Desired       int32                  `protobuf:"varint,1,opt,name=desired,proto3" json:"desired,omitempty"`
	Available     int32                  `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	Claimed       int32                  `protobuf:"varint,3,opt,name=claimed,proto3" json:"claimed,omitempty"`
	Warming       int32                  `protobuf:"varint,4,opt,name=warming,proto3" json:"warming,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolStatus) Reset() {
	*x = PoolStatus{}
	mi := &file_pool_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolStatus) ProtoMessage() {}

func (x *PoolStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pool_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolStatus.ProtoReflect.Descriptor instead.
func (*PoolStatus) Descriptor() ([]byte, []int) {
	return file_pool_proto_rawDescGZIP(), []int{8}
}

func (x *PoolStatus) GetDesired() int32 {
	if x != nil {
		return x.Desired
	}
	return 0
}

func (x *PoolStatus) GetAvailable() int32 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *PoolStatus) GetClaimed() int32 {
	if x != nil {
		return x.Claimed
	}
	return 0
}

func (x *PoolStatus) GetWarming() int32 {
	if x != nil {
		return x.Warming
	}
	return 0
}

var File_pool_proto protoreflect.FileDescriptor

const file_pool_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"pool.proto\x12\x10pool.operator.v1\"\"\n" +
	"\fClaimRequest\x12\x12\n" +
	"\x04pool\x18\x01 \x01(\tR\x04pool\"w\n" +
	"\rClaimResponse\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12\x15\n" +
	"\x06pod_ip\x18\x02 \x01(\tR\x05podIp\x12\x19\n" +
	"\bpod_port\x18\x03 \x01(\x05R\apodPort\x12\x19\n" +
	"\bclaim_id\x18\x04 \x01(\tR\aclaimId\")\n" +
	"\fRenewRequest\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\".\n" +
	"\rRenewResponse\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x01 \x01(\tR\texpiresAt\"+\n" +
	"\x0eReleaseRequest\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\"\x11\n" +
	"\x0fReleaseResponse\"\x0f\n" +
	"\rStatusRequest\"\xab\x01\n" +
	"\x0eStatusResponse\x12A\n" +
	"\x05pools\x18\x01 \x03(\v2+.pool.operator.v1.StatusResponse.PoolsEntryR\x05pools\x1aV\n" +
	"\n" +
	"PoolsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.pool.operator.v1.PoolStatusR\x05value:\x028\x01\"x\n" +
	"\n" +
	"PoolStatus\x12\x18\n" +
	"\adesired\x18\x01 \x01(\x05R\adesired\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\x05R\tavailable\x12\x18\n" +
	"\aclaimed\x18\x03 \x01(\x05R\aclaimed\x12\x18\n" +
	"\awarming\x18\x04 \x01(\x05R\awarming2\xbe\x02\n" +
	"\vPoolService\x12H\n" +
	"\x05Claim\x12\x1e.pool.operator.v1.ClaimRequest\x1a\x1f.pool.operator.v1.ClaimResponse\x12H\n" +
	"\x05Renew\x12\x1e.pool.operator.v1.RenewRequest\x1a\x1f.pool.operator.v1.RenewResponse\x12N\n" +
	"\aRelease\x12 .pool.operator.v1.ReleaseRequest\x1a!.pool.operator.v1.ReleaseResponse\x12K\n" +
	"\x06Status\x12\x1f.pool.operator.v1.StatusRequest\x1a .pool.operator.v1.StatusResponseB?Z=github.com/siyanzhu/agentic-platform/pool-operator/pkg/poolpbb\x06proto3"

var (
	file_pool_proto_rawDescOnce sync.Once
	file_pool_proto_rawDescData []byte
)

func file_pool_proto_rawDescGZIP() []byte {
	file_pool_proto_rawDescOnce.Do(func() {
		file_pool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pool_proto_rawDesc), len(file_pool_proto_rawDesc)))
	})
	return file_pool_proto_rawDescData
}

var file_pool_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pool_proto_goTypes = []any{
	(*ClaimRequest)(nil),    // 0: pool.operator.v1.ClaimRequest
	(*ClaimResponse)(nil),   // 1: pool.operator.v1.ClaimResponse
	(*RenewRequest)(nil),    // 2: pool.operator.v1.RenewRequest
	(*RenewResponse)(nil),   // 3: pool.operator.v1.RenewResponse
	(*ReleaseRequest)(nil),  // 4: pool.operator.v1.ReleaseRequest
	(*ReleaseResponse)(nil), // 5: pool.operator.v1.ReleaseResponse
	(*StatusRequest)(nil),   // 6: pool.operator.v1.StatusRequest
	(*StatusResponse)(nil),  // 7: pool.operator.v1.StatusResponse
	(*PoolStatus)(nil),      // 8: pool.operator.v1.PoolStatus
	nil,                     // 9: pool.operator.v1.StatusResponse.PoolsEntry
}
var file_pool_proto_depIdxs = []int32{
	9, // 0: pool.operator.v1.StatusResponse.pools:type_name -> pool.operator.v1.StatusResponse.PoolsEntry
	8, // 1: pool.operator.v1.StatusResponse.PoolsEntry.value:type_name -> pool.operator.v1.PoolStatus
	0, // 2: pool.operator.v1.PoolService.Claim:input_type -> pool.operator.v1.ClaimRequest
	2, // 3: pool.operator.v1.PoolService.Renew:input_type -> pool.operator.v1.RenewRequest
	4, // 4: pool.operator.v1.PoolService.Release:input_type -> pool.operator.v1.ReleaseRequest
	6, // 5: pool.operator.v1.PoolService.Status:input_type -> pool.operator.v1.StatusRequest
	1, // 6: pool.operator.v1.PoolService.Claim:output_type -> pool.operator.v1.ClaimResponse
	3, // 7: pool.operator.v1.PoolService.Renew:output_type -> pool.operator.v1.RenewResponse
	5, // 8: pool.operator.v1.PoolService.Release:output_type -> pool.operator.v1.ReleaseResponse
	7, // 9: pool.operator.v1.PoolService.Status:output_type -> pool.operator.v1.StatusResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pool_proto_init() }
func file_pool_proto_init() {
	if File_pool_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pool_proto_rawDesc), len(file_pool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pool_proto_goTypes,
		DependencyIndexes: file_pool_proto_depIdxs,
		MessageInfos:      file_pool_proto_msgTypes,
	}.Build()
	File_pool_proto = out.File
	file_pool_proto_goTypes = nil
	file_pool_proto_depIdxs = nil
}
